// Single source of truth for seed data + automatic DB provisioning.
// Used by /api/seed (manual) and instrumentation (automatic on startup).

import { db } from "@/db";
import {
  lawyers,
  reviews,
  contracts,
  articles,
  qaQuestions,
} from "@/db/schema";
import { sql } from "drizzle-orm";

const DAY = 86400000;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY);

/* ----------------------------- Seed data ----------------------------- */
const lawyerData = [
  { slug: "sohrab-mohammadi", name: "دکتر سهراب محمدی", avatarColor: "#15365d", title: "وکیل پایه یک دادگستری", licenseNo: "۱۲۳۴۵/تهران", city: "تهران", province: "تهران", gender: "male", experienceYears: 16, specialties: ["خانواده", "طلاق", "ارث"], rating: 4.9, reviewCount: 312, caseCount: 540, priceChat: 120000, priceVoice: 350000, priceVideo: 600000, topRated: true, fastResponder: true, contractExpert: false, responseTime: "کمتر از ۳۰ دقیقه", bio: "متخصص دعاوی خانواده با ۱۶ سال سابقه؛ تمرکز بر طلاق توافقی و یک‌طرفه، مهریه و حضانت.", about: "دکتر سهراب محمدی دانش‌آموخته حقوق خصوصی و عضو کانون وکلای دادگستری مرکز است. ایشان با رویکرد میانجی‌گری، تلاش می‌کند دعاوی خانواده با کمترین تنش و در کوتاه‌ترین زمان به نتیجه برسد. تجربه گسترده در پرونده‌های مهریه، نفقه، اجرت‌المثل و حضانت را داراست.", services: ["مشاوره طلاق توافقی", "مطالبه مهریه", "حضانت فرزندان", "تنظیم دادخواست خانواده"], views: 8420, featured: true },
  { slug: "neda-karimi", name: "ندا کریمی", avatarColor: "#946809", title: "وکیل پایه یک دادگستری", licenseNo: "۸۷۶۵۴/اصفهان", city: "اصفهان", province: "اصفهان", gender: "female", experienceYears: 12, specialties: ["ملک", "قراردادها"], rating: 4.8, reviewCount: 198, caseCount: 360, priceChat: 100000, priceVoice: 300000, priceVideo: 500000, topRated: true, fastResponder: false, contractExpert: true, responseTime: "کمتر از ۲ ساعت", bio: "وکیل تخصصی املاک؛ تخلیه، الزام به تنظیم سند، تصرف عدوانی و تنظیم قرارداد اجاره.", about: "خانم ندا کریمی عضو کانون وکلای استان اصفهان و متخصص حقوق ملک است. ایشان در زمینه دعاوی تخلیه، مطالبه اجاره‌بها، الزام به تنظیم سند رسمی و تصرف عدوانی تجربه گسترده‌ای دارد و قراردادهای اجاره امن تهیه می‌کند.", services: ["تخلیه ملک", "الزام به تنظیم سند", "تصرف عدوانی", "تنظیم قرارداد اجاره"], views: 5310, featured: true },
  { slug: "amirhossein-rostami", name: "امیرحسین رستمی", avatarColor: "#1d6a3f", title: "وکیل پایه یک دادگستری", licenseNo: "۴۵۳۲۱/خراسان رضوی", city: "مشهد", province: "خراسان رضوی", gender: "male", experienceYears: 9, specialties: ["کیفری", "قراردادها"], rating: 4.7, reviewCount: 142, caseCount: 210, priceChat: 110000, priceVoice: 320000, priceVideo: 520000, topRated: false, fastResponder: true, contractExpert: false, responseTime: "کمتر از یک ساعت", bio: "دفاع کیفری در جرایم کلاهبرداری، خیانت در امانت، جعل و سرقت؛ پاسخ‌گویی سریع.", about: "آقای امیرحسین رستمی وکیل پایه یک و عضو کانون وکلای خراسان رضوی است. تخصص ایشان دعاوی کیفری به‌ویژه کلاهبرداری، خیانت در امانت، جعل و سرقت است و در مرحله دادسرا و دادگاه دفاع می‌کند.", services: ["شکایت کلاهبرداری", "دفاع کیفری", "تنظیم شکواییه", "اعاده اعتبار"], views: 4120, featured: true },
  { slug: "mahsa-ebrahimi", name: "دکتر مهسا ابراهیمی", avatarColor: "#7a2e7d", title: "وکیل پایه یک دادگستری", licenseNo: "۹۹۱۱۲/تهران", city: "تهران", province: "تهران", gender: "female", experienceYears: 14, specialties: ["قراردادها", "تجارت", "شرکت‌ها"], rating: 5.0, reviewCount: 267, caseCount: 430, priceChat: 150000, priceVoice: 400000, priceVideo: 700000, topRated: true, fastResponder: true, contractExpert: true, responseTime: "کمتر از یک ساعت", bio: "متخصص حقوق قراردادها و شرکت‌ها؛ تنظیم و بررسی قراردادهای تجاری و بین‌المللی.", about: "دکتر مهسا ابراهیمی دکترای حقوق تجاری و مشاور حقوقی چند شرکت بزرگ است. تخصص ایشان تنظیم و بازبینی قراردادهای تجاری، مشارکت، تأمین و قراردادهای استارتاپی است و به کسب‌وکارها مشاوره ثابت می‌دهد.", services: ["تنظیم قرارداد تجاری", "بررسی قرارداد", "مشاوره شرکت‌ها", "قرارداد سرمایه‌گذاری"], views: 7240, featured: true },
  { slug: "reza-najafi", name: "رضا نجفی", avatarColor: "#2a5d8f", title: "وکیل پایه یک دادگستری", licenseNo: "۳۳۰۹۸/آذربایجان شرقی", city: "تبریز", province: "آذربایجان شرقی", gender: "male", experienceYears: 18, specialties: ["تجارت", "شرکت‌ها", "مالیاتی"], rating: 4.6, reviewCount: 121, caseCount: 280, priceChat: 130000, priceVoice: 360000, priceVideo: 580000, topRated: false, fastResponder: false, contractExpert: true, responseTime: "کمتر از ۳ ساعت", bio: "حقوق تجارت و شرکت‌ها با ۱۸ سال سابقه؛ ثبت، تغییرات و دعاوی تجاری.", about: "آقای رضا نجفی از وکلای باتجربه استان آذربایجان شرقی در حوزه تجارت و شرکت‌هاست. ایشان در ثبت شرکت، تنظیم صورتجلسات و دعاوی تجاری فعالیت دارد.", services: ["ثبت شرکت", "دعاوی تجاری", "مشاوره مالیاتی", "تغییرات شرکت"], views: 2980, featured: false },
  { slug: "sara-mousavi", name: "سارا موسوی", avatarColor: "#b07d12", title: "وکیل پایه یک دادگستری", licenseNo: "۲۲۳۱۱/فارس", city: "شیراز", province: "فارس", gender: "female", experienceYears: 11, specialties: ["ارث", "خانواده"], rating: 4.8, reviewCount: 156, caseCount: 240, priceChat: 95000, priceVoice: 280000, priceVideo: 480000, topRated: true, fastResponder: false, contractExpert: false, responseTime: "کمتر از ۲ ساعت", bio: "متخصص امور حسبی؛ انحصار وراثت، تقسیم ترکه و وصیت‌نامه.", about: "خانم سارا موسوی عضو کانون وکلای فارس و متخصص امور ارث و انحصار وراثت است. ایشان در اخذ گواهی انحصار وراثت، تقسیم ترکه و حل‌وفصل اختلافات وراث تجربه دارد.", services: ["انحصار وراثت", "تقسیم ترکه", "وصیت‌نامه", "دعاوی ارث"], views: 3650, featured: false },
  { slug: "kaveh-ahmadi", name: "کاوه احمدی", avatarColor: "#8f2a2a", title: "وکیل پایه یک دادگستری", licenseNo: "۷۷۰۱۲/البرز", city: "کرج", province: "البرز", gender: "male", experienceYears: 8, specialties: ["چک و اسناد", "قراردادها"], rating: 4.7, reviewCount: 178, caseCount: 320, priceChat: 90000, priceVoice: 260000, priceVideo: 440000, topRated: false, fastResponder: true, contractExpert: false, responseTime: "کمتر از یک ساعت", bio: "متخصص چک برگشتی، سفته و مطالبات؛ پیگیری سریع از طریق اجرائیه.", about: "آقای کاوه احمدی وکیل پایه یک و متخصص اسناد تجاری است. ایشان در مطالبه وجه چک برگشتی، سفته و وصول مطالبات از مسیر اجرائیه و دعاوی حقوقی تخصص دارد و پاسخ‌گویی سریعی ارائه می‌دهد.", services: ["مطالبه چک برگشتی", "اجرائیه", "تنظیم اظهارنامه", "وصول مطالبات"], views: 4870, featured: false },
  { slug: "leila-sadeghi", name: "دکتر لیلا صادقی", avatarColor: "#0e7c7b", title: "وکیل پایه یک دادگستری", licenseNo: "۶۶۵۴۳/گیلان", city: "رشت", province: "گیلان", gender: "female", experienceYears: 13, specialties: ["خانواده", "طلاق"], rating: 4.9, reviewCount: 203, caseCount: 380, priceChat: 105000, priceVoice: 300000, priceVideo: 520000, topRated: true, fastResponder: true, contractExpert: false, responseTime: "کمتر از یک ساعت", bio: "وکیل خانواده؛ متخصص مهریه، نفقه و اجرت‌المثل با رویکرد حل مسالمت‌آمیز.", about: "دکتر لیلا صادقی عضو کانون وکلای گیلان و متخصص دعاوی خانواده است. ایشان با تمرکز بر حقوق زنان، در پرونده‌های مهریه، نفقه، اجرت‌المثل و طلاق فعالیت دارد.", services: ["مطالبه مهریه", "نفقه و اجرت‌المثل", "طلاق توافقی", "حضانت"], views: 5920, featured: false },
  { slug: "mohammadreza-ghasemi", name: "محمدرضا قاسمی", avatarColor: "#444b8f", title: "وکیل پایه یک دادگستری", licenseNo: "۵۵۰۲۳/خوزستان", city: "اهواز", province: "خوزستان", gender: "male", experienceYears: 15, specialties: ["مالیاتی", "شرکت‌ها"], rating: 4.5, reviewCount: 98, caseCount: 170, priceChat: 140000, priceVoice: 380000, priceVideo: 620000, topRated: false, fastResponder: false, contractExpert: true, responseTime: "کمتر از ۴ ساعت", bio: "متخصص دعاوی مالیاتی و گمرکی؛ دفاع در کمیسیون‌های مالیاتی.", about: "آقای محمدرضا قاسمی وکیل پایه یک و متخصص حقوق مالیاتی است. ایشان در دعاوی مالیاتی، اعتراض به آرای کمیسیون و امور گمرکی تخصص دارد.", services: ["اعتراض مالیاتی", "دفاع کمیسیون", "مشاوره مالیاتی شرکت", "امور گمرکی"], views: 2140, featured: false },
  { slug: "fateme-nouri", name: "فاطمه نوری", avatarColor: "#9c27b0", title: "وکیل پایه یک دادگستری", licenseNo: "۸۸۹۹۰/مازندران", city: "ساری", province: "مازندران", gender: "female", experienceYears: 10, specialties: ["کار", "خانواده"], rating: 4.7, reviewCount: 134, caseCount: 220, priceChat: 95000, priceVoice: 270000, priceVideo: 450000, topRated: false, fastResponder: true, contractExpert: false, responseTime: "کمتر از ۲ ساعت", bio: "وکیل دعاوی کارگری و کارفرمایی؛ دفاع در اداره کار.", about: "خانم فاطمه نوری وکیل پایه یک و متخصص حقوق کار است. ایشان در دعاوی اخراج، مطالبه حقوق و سنوات و تأخیر تأدیه در هیأت‌های اداره کار فعالیت دارد.", services: ["شکایت اخراج", "مطالبه سنوات", "قرارداد کار", "دفاع اداره کار"], views: 2760, featured: false },
  { slug: "alireza-bahrami", name: "علیرضا بهرامی", avatarColor: "#3a5c3a", title: "وکیل پایه یک دادگستری", licenseNo: "۱۱۲۲۳/قم", city: "قم", province: "قم", gender: "male", experienceYears: 17, specialties: ["ملک", "کیفری"], rating: 4.6, reviewCount: 145, caseCount: 300, priceChat: 100000, priceVoice: 290000, priceVideo: 500000, topRated: false, fastResponder: false, contractExpert: false, responseTime: "کمتر از ۳ ساعت", bio: "متخصص تصرف عدوانی، خلع ید و دعاوی ملکی.", about: "آقای علیرضا بهرامی وکیل پایه یک و متخصص حقوق ملک و کیفری است. ایشان در دعاوی تصرف عدوانی، خلع ید و تخلیه ملک تجربه گسترده‌ای دارد.", services: ["تصرف عدوانی", "خلع ید", "تخلیه ملک", "افراز"], views: 3180, featured: false },
  { slug: "zahra-farahmand", name: "دکتر زهرا فرهمند", avatarColor: "#6a1b9a", title: "وکیل پایه یک دادگستری", licenseNo: "۹۹۰۰۱/تهران", city: "تهران", province: "تهران", gender: "female", experienceYears: 19, specialties: ["مهاجرت", "تجارت"], rating: 4.8, reviewCount: 187, caseCount: 290, priceChat: 160000, priceVoice: 420000, priceVideo: 720000, topRated: true, fastResponder: false, contractExpert: true, responseTime: "کمتر از ۴ ساعت", bio: "متخصص امور مهاجرتی و تجارت بین‌الملل؛ وکالت‌های خارجی و قراردادهای مرزی.", about: "دکتر زهرا فرهمند دکترای حقوق بین‌الملل و متخصص امور مهاجرت و تجارت بین‌الملل است. ایشان در تنظیم قراردادهای بین‌المللی، احراز هویت و وکالت‌های خارجی فعالیت دارد.", services: ["امور مهاجرت", "قرارداد بین‌المللی", "وکالت خارجی", "تجارت مرزی"], views: 3940, featured: false },
  { slug: "hossein-alamdari", name: "حسین علمداری", avatarColor: "#7f3911", title: "وکیل پایه یک دادگستری", licenseNo: "۳۳۴۴۵/خراسان رضوی", city: "مشهد", province: "خراسان رضوی", gender: "male", experienceYears: 12, specialties: ["کیفری"], rating: 4.7, reviewCount: 161, caseCount: 250, priceChat: 115000, priceVoice: 330000, priceVideo: 540000, topRated: false, fastResponder: true, contractExpert: false, responseTime: "کمتر از یک ساعت", bio: "دفاع کیفری تخصصی؛ کلاهبرداری، خیانت در امانت و جرایم اقتصادی.", about: "آقای حسین علمداری وکیل پایه یک و متخصص دفاع کیفری در جرایم اقتصادی است. ایشان در پرونده‌های کلاهبرداری، خیانت در امانت و جرایم رایانه‌ای دفاع می‌کند.", services: ["دفاع کلاهبرداری", "خیانت در امانت", "جرایم رایانه‌ای", "تنظیم شکواییه"], views: 3520, featured: false },
  { slug: "negar-soleimani", name: "نگار سلیمانی", avatarColor: "#1565c0", title: "وکیل پایه یک دادگستری", licenseNo: "۴۴۵۵۶/البرز", city: "کرج", province: "البرز", gender: "female", experienceYears: 9, specialties: ["ثبت برند", "شرکت‌ها", "قراردادها"], rating: 4.8, reviewCount: 129, caseCount: 200, priceChat: 110000, priceVoice: 310000, priceVideo: 510000, topRated: false, fastResponder: true, contractExpert: true, responseTime: "کمتر از ۲ ساعت", bio: "متخصص مالکیت فکری؛ ثبت برند، علامت تجاری و اختراع.", about: "خانم نگار سلیمانی وکیل پایه یک و متخصص مالکیت فکری و امور ثبتی است. ایشان در ثبت برند، علامت تجاری و اختراع و دعاوی نقض حقوق مالکیت فکری تخصص دارد.", services: ["ثبت برند", "ثبت علامت تجاری", "ثبت اختراع", "دعوای نقض"], views: 4010, featured: false },
];

const reviewData = [
  { lawyerId: 1, clientName: "محمد ر.", rating: 5, comment: "بسیار حرفه‌ای و صبور، پرونده طلاق توافقی در کمترین زمان انجام شد.", service: "مشاوره طلاق", createdAt: daysAgo(8) },
  { lawyerId: 1, clientName: "سارا ک.", rating: 5, comment: "مهریه‌ام را بدون دردسر وصول کردم. ممنونم.", service: "مطالبه مهریه", createdAt: daysAgo(21) },
  { lawyerId: 2, clientName: "رضا م.", rating: 5, comment: "قرارداد اجاره‌ای عالی تنظیم کرد و مشکل تخلیه را حل کرد.", service: "تنظیم قرارداد", createdAt: daysAgo(5) },
  { lawyerId: 4, clientName: "شرکت آرمان", rating: 5, comment: "بررسی قرارداد سرمایه‌گذاری دقیق و کامل بود. توصیه می‌کنم.", service: "بررسی قرارداد", createdAt: daysAgo(12) },
  { lawyerId: 4, clientName: "الهام ت.", rating: 4, comment: "تخصص بالا در قراردادهای تجاری، فقط زمان پاسخ‌گویی کمی طولانی بود.", service: "تنظیم قرارداد", createdAt: daysAgo(30) },
  { lawyerId: 8, clientName: "زهرا ع.", rating: 5, comment: "وکیل دلسوز و متخصص؛ نفقه‌ام را تأمین کردم.", service: "مشاوره نفقه", createdAt: daysAgo(3) },
  { lawyerId: 7, clientName: "حسن ب.", rating: 5, comment: "چک برگشتی را خیلی سریع پیگیری کرد و وجه را وصول کردم.", service: "مطالبه چک", createdAt: daysAgo(6) },
  { lawyerId: 3, clientName: "کریم ن.", rating: 5, comment: "دفاع کیفری قوی، برائت گرفتم. سپاسگزارم.", service: "دفاع کیفری", createdAt: daysAgo(15) },
];

const contractData = [
  { slug: "aghrarname-ejare-melk", title: "قرارداد اجاره ملک (مسکونی/تجاری)", category: "اجاره", icon: "home", description: "قرارداد اجاره استاندارد و مطمئن با رعایت قانون روابط موجر و مستأجر.", useCase: "برای اجاره ملک مسکونی یا تجاری بین موجر و مستأجر؛ تعیین ودیعه، اجاره‌بها و مدت.", risks: ["نبود شرط تخلیه مشخص", "عدم تعیین دقیق هزینه‌های شارژ و آب/برق", "تاریخ وصول اجاره‌بها نامشخص"], keyClauses: ["مشخصات موجر و مستأجر", "ودیعه و اجاره‌بها و نحوه پرداخت", "مدت اجاره و شرط تمدید", "تعهدات موجر و مستأجر", "شرط تخلیه و خلع ید"], samplePrice: 250000, customPrice: 850000, popular: true, steps: ["مشخصات موجر", "مشخصات مستأجر", "مشخصات ملک", "مبلغ ودیعه و اجاره", "مدت اجاره", "شروط خاص", "تعهدات طرفین", "خروجی قرارداد"] },
  { slug: "aghrarname-kharid-forush-melk", title: "قرارداد خرید و فروش ملک", category: "خرید و فروش", icon: "home", description: "مبایعه‌نامه دقیق با تعیین محلس‌الوصول، زمان تحویل و ضمانت اجرا.", useCase: "برای انتقال قطعی مالکیت ملک با رعایت شرایط قانونی و مالیاتی.", risks: ["نبود ضمانت اجرای پرداخت", "مبهم بودن زمان تحویل", "مسئولیت مالیاتی نامشخص"], keyClauses: ["مشخصات طرفین و ملک", "ثمن و نحوه پرداخت", "زمان تحویل و تحویل سند", "ضمانت اجرای تخلف", "مسئولیت هزینه‌های انتقال"], samplePrice: 300000, customPrice: 950000, popular: true, steps: ["مشخصات خریدار و فروشنده", "مشخصات ملک", "مبلغ معامله", "نحوه پرداخت", "زمان تحویل", "شروط فسخ", "خروجی قرارداد"] },
  { slug: "aghrarname-mosharekat-madani", title: "قرارداد مشارکت مدنی", category: "مشارکت", icon: "briefcase", description: "تعیین دقیق سهم سود و زیان، مدیریت و خروج در مشارکت‌ها.", useCase: "برای مشارکت دو یا چند نفر در یک فعالیت اقتصادی با تقسیم سود و زیان.", risks: ["نامشخص بودن سهم سود و زیان", "نبود شرط خروج", "ابهام در مدیریت"], keyClauses: ["سهم هر طرف", "مدت مشارکت", "نحوه مدیریت", "تقسیم سود و زیان", "شرط خروج و فسخ"], samplePrice: 350000, customPrice: 1100000, popular: false, steps: ["مشخصات شرکا", "موضوع مشارکت", "سهم هر طرف", "مدت", "تقسیم سود", "شرط خروج", "خروجی قرارداد"] },
  { slug: "aghrarname-peymanchari-sakhteman", title: "قرارداد پیمانکاری ساختمان", category: "پیمانکاری", icon: "building", description: "تعهدات مقاطعه‌کار و پیمانکار با جریمه تأخیر و ضمانت حسن انجام کار.", useCase: "برای ساخت‌وساز و پروژه‌های عمرانی میان کارفرما و پیمانکار.", risks: ["نبود جریمه تأخیر", "ضمانت حسن انجام ناکافی", "تغییرات دامنه پروژه نامشخص"], keyClauses: ["دامنه کار", "مبلغ و زمان‌بندی پرداخت", "مدت اجرا و جریمه تأخیر", "ضمانت حسن انجام", "تسویه و تحویل"], samplePrice: 400000, customPrice: 1300000, popular: false, steps: ["مشخصات کارفرما و پیمانکار", "دامنه پروژه", "مبلغ و پرداخت", "مدت و جریمه", "ضمانت", "خروجی قرارداد"] },
  { slug: "aghrarname-estekhdam", title: "قرارداد استخدام", category: "استخدام", icon: "briefcase", description: "تعیین حقوق، ساعات کار، مرخصی و تعهدات طرفین مطابق قانون کار.", useCase: "برای رابطه کارگری-کارفرمایی با تعیین دستمزد و شرایط کار.", risks: ["دست‌مزد کمتر از حداقل قانونی", "نبود تعیین ساعات کار", "تعهد اضافه‌کاری نامشخص"], keyClauses: ["نوع کار و ساعت کاری", "دست‌مزد و مزایا", "مرخصی و بیمه", "مدت قرارداد", "شرایط اخراج"], samplePrice: 200000, customPrice: 700000, popular: true, steps: ["مشخصات کارگر و کارفرما", "نوع کار", "دست‌مزد", "ساعت کار", "بیمه و مرخصی", "خروجی قرارداد"] },
  { slug: "aghrarname-mahramiyat-nda", title: "قرارداد محرمانگی (NDA)", category: "قرارداد محرمانگی (NDA)", icon: "lock", description: "حفاظت از اطلاعات تجاری و اسرار با جریمه افشا.", useCase: "برای مذاکرات تجاری، استارتاپ‌ها و همکاری‌هایی که نیاز به رازداری دارند.", risks: ["تعریف مبهم از اطلاعات محرمانه", "نبود جریمه افشا", "مدت تعهد طولانی‌تر از ضرورت"], keyClauses: ["تعریف اطلاعات محرمانه", "تعهدات طرفین", "استثنائات", "مدت تعهد", "جریمه افشا"], samplePrice: 180000, customPrice: 600000, popular: false, steps: ["مشخصات طرفین", "تعریف اطلاعات محرمانه", "تعهدات", "مدت", "جریمه", "خروجی قرارداد"] },
  { slug: "aghrarname-sarmaye-gozari", title: "قرارداد سرمایه‌گذاری", category: "سرمایه‌گذاری", icon: "money", description: "تعیین سهم سرمایه‌گذار، حقوق مالکانه و خروج سرمایه‌گذار.", useCase: "برای جذب سرمایه در استارتاپ‌ها و کسب‌وکارها.", risks: ["سهم مالکانه ناعادلانه", "نبود شرط خروج سرمایه‌گذار", "حقوق رای نامشخص"], keyClauses: ["مبلغ سرمایه‌گذاری", "سهم مالکانه", "حقوق و تعهدات", "شرط خروج", "حل‌وفصل اختلاف"], samplePrice: 500000, customPrice: 1800000, popular: true, steps: ["مشخصات طرفین", "مبلغ سرمایه‌گذاری", "سهم مالکانه", "حقوق رای", "خروج", "خروجی قرارداد"] },
  { slug: "aghrarname-sherkat", title: "قرارداد شراکت (تأسیس)", category: "شراکت", icon: "building", description: "تأسیس شراکت با تعیین سهم، مدیریت و تقسیم سود.", useCase: "برای راه‌اندازی شرکتی با چند شریک.", risks: ["سهم ناعادلانه", "مدیریت نامشخص", "نبود شرط خروج شریک"], keyClauses: ["سهم هر شریک", "نحوه مدیریت", "تقسیم سود", "ورود و خروج شریک", "حل اختلاف"], samplePrice: 380000, customPrice: 1200000, popular: false, steps: ["مشخصات شرکا", "سهم‌ها", "مدیریت", "تقسیم سود", "خروج", "خروجی قرارداد"] },
  { slug: "dadkhasat-talaq-tavafoghi", title: "دادخواست طلاق توافقی", category: "دادخواست", icon: "gavel", description: "دادخواست استاندارد طلاق توافقی با تعیین شرایط توافق‌شده.", useCase: "برای ثبت درخواست طلاق توافقی در دادگاه خانواده.", risks: ["نقص مدارک توافق", "اشتباه در تعیین دادگاه صالح"], keyClauses: ["مشخصات زوجین", "نوع طلاق", "توافق مالی", "حضانت فرزندان", "خواسته"], samplePrice: 220000, customPrice: 750000, popular: true, steps: ["مشخصات زوجین", "نوع طلاق", "توافق مالی", "حضانت", "خواسته", "خروجی دادخواست"] },
  { slug: "shokavye-kolahbardari", title: "شکواییه کلاهبرداری", category: "شکواییه", icon: "gavel", description: "شکواییه کیفری برای طرح شکایت کلاهبرداری با ذکر وقایع و ادله.", useCase: "برای ثبت شکایت کیفری در دادسرا.", risks: ["نبود ادله کافی", "اشتباه در تعیین مرجع"], keyClauses: ["مشخصات شاکی و مشتکی‌عنه", "شرح وقایع", "ادله", "مستندات", "خواسته"], samplePrice: 200000, customPrice: 680000, popular: false, steps: ["مشخصات طرفین", "شرح وقایع", "ادله", "خواسته", "خروجی شکواییه"] },
  { slug: "ozharname-motalebe-vej", title: "اظهارنامه مطالبه وجه", category: "اظهارنامه", icon: "mail", description: "اظهارنامه رسمی برای مطالبه وجه چک یا طلب پیش از اقامه دعوا.", useCase: "برای اخطار رسمی مطالبه طلب از بدهکار.", risks: ["نبود مهلت منطقی", "اشتباه در مشخصات گیرنده"], keyClauses: ["مشخصات اظهارکننده و گیرنده", "موضوع طلب", "مبلغ", "مهلت پرداخت", "اخطار اقدام قانونی"], samplePrice: 150000, customPrice: 500000, popular: false, steps: ["مشخصات طرفین", "موضوع طلب", "مبلغ", "مهلت", "اخطار", "خروجی اظهارنامه"] },
  { slug: "aghrarname-namayandegi", title: "قرارداد نمایندگی فروش", category: "نمایندگی", icon: "truck", description: "اعطای نمایندگی فروش با تعیین منطقه، پورسانت و تعهدات.", useCase: "برای اعطای حق فروش محصولات در منطقه‌ای مشخص.", risks: ["منطقه نمایندگی نامشخص", "پورسانت مبهم", "نبود شرط انحصاری روشن"], keyClauses: ["منطقه نمایندگی", "پورسانت", "تعهدات نماینده", "مدت", "فسخ"], samplePrice: 280000, customPrice: 900000, popular: false, steps: ["مشخصات طرفین", "منطقه", "پورسانت", "تعهدات", "مدت", "خروجی قرارداد"] },
];

const articleData = [
  { slug: "check-bargasht-che-konim", title: "اگر چک برگشت بخورد چه کار کنیم؟", category: "چک و اسناد", excerpt: "راهنمای گام‌به‌گام پیگیری چک برگشتی؛ از اخذ گواهی عدم پرداخت تا اجرائیه و دادگاه.", content: "وقتی چکی برگشت می‌خورد، دارنده چک گزینه‌های قانونی متعددی برای وصول طلب خود دارد. نخستین گام، مراجعه به بانک و اخذ «گواهی عدم پرداخت» به همراه نسخه اجرائیه است.\n\nپس از اخذ گواهی، دارنده می‌تواند از دو مسیر اقدام کند: مسیر سریع «اجرائیه» از طریق اجرای احکام، و مسیر شکایت کیفری یا حقوقی در دادگاه. اجرائیه معمولاً سریع‌ترین روش وصول وجه است.\n\nباید توجه داشت که برای طرح شکایت کیفری مهلت قانونی وجود دارد و تأخیر می‌تواند موجب سقوط حق شود. همچنین داشتن نشانی دقیق صادرکننده چک برای احضار او ضروری است.\n\nدر نهایت، برای چک‌های صیادی، اطلاعات در سامانه صیاد ثبت و ردیابی می‌شود. مشاوره با وکیل متخصص اسناد تجاری می‌تواند مسیر درست را مشخص کند و زمان و هزینه را بهینه‌سازی نماید.", readTime: 6, author: "تیم تحریریه شریفمند", authorRole: "پژوهشگر حقوق", views: 12400, publishedAt: daysAgo(4) },
  { slug: "marahel-talaq-tavafoghi", title: "مراحل طلاق توافقی در چند گام ساده", category: "خانواده", excerpt: "طلاق توافقی سریع‌ترین مسیر جدایی است؛ در این مقاله مراحل کامل آن را مرور می‌کنیم.", content: "طلاق توافقی زمانی مطرح می‌شود که زوجین در مورد تمام امور از جمله مهریه، نفقه، اجرت‌المثل و حضانت فرزندان به توافق رسیده باشند. این نوع طلاق بسیار سریع‌تر و کم‌هزینه‌تر از طلاق یک‌طرفه است.\n\nنخستین گام، توافق کتبی روی امور مالی و حضانت است. سپس دادخواست طلاق توافقی در دادگاه خانواده ثبت می‌شود. دادگاه پس از بررسی، جلسه‌ای تعیین و در صورت تأیید توافق، گواهی عدم امکان سازش صادر می‌کند.\n\nپس از صدور گواهی، طلاق باید در محضر رسمی ثبت شود تا آثار حقوقی کامل پیدا کند. در طول این فرایند، مراجعه به مشاور خانواده الزامی است.\n\nبا کمک وکیل متخصص خانواده می‌توان پیش‌نویس توافق‌نامه را دقیق تنظیم کرد تا از توقف فرایند در مراحل بعدی جلوگیری شود.", readTime: 5, author: "دکتر لیلا صادقی", authorRole: "وکیل پایه یک", views: 9800, publishedAt: daysAgo(9) },
  { slug: "aghrarname-ejare-amin", title: "چگونه قرارداد اجاره امن ببندیم؟", category: "ملک", excerpt: "نکات کلیدی برای بستن قرارداد اجاره‌ای که حقوق موجر و مستأجر را حفظ می‌کند.", content: "قرارداد اجاره یکی از پرکاربردترین قراردادهای حقوقی است. یک قرارداد خوب باید مشخصات دقیق ملک، مبلغ ودیعه و اجاره‌بها، مدت اجاره و شرط تخلیه را به‌طور روشن ذکر کند.\n\nیکی از مهم‌ترین بندها، «شرط تخلیه» است که به موجر اجازه می‌دهد در صورت عدم پرداخت اجاره‌بها، فرایند تخلیه را از طریق شورای حل اختلاف پیگیری کند. نبود این شرط، تخلیه را بسیار دشوار می‌سازد.\n\nهمچنین تعیین اینکه کدام طرف مسئول پرداخت شارژ، آب، برق و گاز است، باید مشخص باشد. تاریخ دقیق پرداخت اجاره‌بها نیز از اختلافات جلوگیری می‌کند.\n\nثبت قرارداد در سامانه اجاره و استفاده از فرمت قراردادهای رسمی، حقوق طرفین را تقویت می‌کند. مشاوره با وکیل ملکی پیش از امضا، ریسک‌ها را به حداقل می‌رساند.", readTime: 4, author: "ندا کریمی", authorRole: "وکیل پایه یک", views: 7600, publishedAt: daysAgo(15) },
  { slug: "tafavot-vakil-payeh-yek-moshaver", title: "تفاوت وکیل پایه یک و مشاور حقوقی چیست؟", category: "آموزش", excerpt: "بسیاری این دو عنوان را اشتباه می‌گیرند؛ در این مقاله تفاوت‌های حقوقی و کاربردی را توضیح می‌دهیم.", content: "وکیل پایه یک دادگستری شخصی است که پس از طی دوره کارآموزی و قبولی در آزمون کانون وکلا، پروانه وکالت دریافت کرده و حق دادرسی و نمایندگی در دادگاه‌ها را دارد.\n\nدر مقابل، مشاور حقوقی لزوماً پروانه وکالت ندارد و نقش او مشاوره‌ای است؛ یعنی می‌تواند نظرات حقوقی ارائه دهد اما معمولاً حق نمایندگی قضایی در دادگاه را نخواهد داشت.\n\nاین تفاوت در پرونده‌های دادگاهی اهمیت زیادی دارد؛ تنها وکیل دارای پروانه می‌تواند در جلسات دادگاه حاضر شود و دفاع کند.\n\nبنابراین پیش از سپردن پرونده، از داشتن پروانه وکالت معتبر و عضویت در کانون وکلا اطمینان حاصل کنید. در پلتفرم شریفمند، همه وکلا احراز هویت و پروانه آن‌ها راستی‌آزمایی می‌شود.", readTime: 4, author: "تیم تحریریه شریفمند", authorRole: "پژوهشگر حقوق", views: 11200, publishedAt: daysAgo(20) },
  { slug: "shakayat-kolahbardari", title: "مراحل شکایت از کلاهبرداری", category: "کیفری", excerpt: "اگر قربانی کلاهبرداری شده‌اید، این راهنمای گام‌به‌گام را دنبال کنید.", content: "کلاهبرداری یکی از جرایم رایج است که در آن شخص با فریب، مال دیگری را به‌تصرف درمی‌آورد. نخستین گام پس از اطمینان از وقوع جرم، جمع‌آوری ادله شامل پیام‌ها، رسیدها و شهود است.\n\nسپس شکایت در دفاتر خدمات الکترونیک قضایی ثبت و به دادسرای صالح ارجاع می‌شود. در شکایت، باید وقایع به‌طور دقیق و با ذکر زمان، مکان و اشخاص توصیف شود.\n\nدادسرا پس از تحقیق، در صورت احراز اولیه، کیفرخواست صادر و پرونده به دادگاه کیفری ارسال می‌گردد. در طول فرایند، داشتن وکیل کیفری می‌تواند در جمع‌آوری ادله و دفاع مؤثر باشد.\n\nتوجه داشته باشید که سرعت در اقدام و حفظ ادله دیجیتال، نقش مهمی در نتیجه پرونده دارد.", readTime: 5, author: "حسین علمداری", authorRole: "وکیل پایه یک", views: 8900, publishedAt: daysAgo(25) },
  { slug: "sabt-brand-hoghoghi", title: "نکات حقوقی ثبت برند و علامت تجاری", category: "شرکت‌ها", excerpt: "چرا ثبت برند اهمیت دارد و چه مراحلی دارد؟ راهنمای کارآفرینان.", content: "ثبت برند یا علامت تجاری، هویت منحصربه‌فرد کسب‌وکار شما را قانوناً محافظت می‌کند و مانع استفاده دیگران از نام و لوگوی شما می‌شود.\n\nبرای ثبت، ابتدا باید از عدم تشابه برند با علائم ثبت‌شده قبلی اطمینان حاصل کنید. سپس درخواست ثبت در سازمان مالکیت معنوی ثبت می‌شود.\n\nپس از بررسی کارشناسان و رفع نقص‌های احتمالی، برند به نام شما ثبت و گواهی صادر می‌گردد. این ثبت معمولاً برای ۱۰ سال معتبر است.\n\nعدم ثبت برند، ریسک سوءاستفاده و حتی از دست دادن نام تجاری را به همراه دارد. مشاوره با وکیل مالکیت فکری می‌تواند روند ثبت را تسریع و از رد درخواست جلوگیری کند.", readTime: 5, author: "نگار سلیمانی", authorRole: "وکیل پایه یک", views: 6400, publishedAt: daysAgo(30) },
  { slug: "hoghogh-kargar-ekhraj", title: "حقوق کارگر در صورت اخراج نابجا", category: "کار", excerpt: "اگر به‌ناحق اخراج شده‌اید، چه حقوقی دارید و چگونه اقدام کنید؟", content: "اخراج نابجا یکی از رایج‌ترین اختلافات کارگری است. طبق قانون کار، کارفرما تنها با دلایل موجه و رعایت تشریفات می‌تواند قرارداد کار را فسخ کند.\n\nکارگری که به‌ناحق اخراج شده، می‌تواند ظرف مهلت قانونی در اداره کار شکایت ثبت کند. هیأت تشخیص ابتدا رسیدگی و در صورت لزوم پرونده به هیأت حل اختلاف ارجاع می‌شود.\n\nدر صورت احراز اخراج نابجا، حکم به بازگشت به کار یا پرداخت حقوق ایام بی‌کاری و سنوات داده می‌شود. داشتن قرارداد کار و فیش حقوقی ادله مهمی هستند.\n\nمشاوره با وکیل متخصص حقوق کار می‌تواند شانس موفقیت در اداره کار را افزایش دهد.", readTime: 4, author: "فاطمه نوری", authorRole: "وکیل پایه یک", views: 7200, publishedAt: daysAgo(33) },
  { slug: "mehrieh-taklif-ghanooni", title: "مهریه؛ تکلیف قانونی و روش‌های مطالبه", category: "خانواده", excerpt: "مهریه حق قانونی زوجه است؛ در این مقاله روش‌های مطالبه مهریه از اجرای ثبت تا دادگاه را بررسی می‌کنیم.", content: "مهریه حقی است که به‌محض عقد نکاح برای زوجه ایجاد می‌شود. مطالبه آن دو مسیر اصلی دارد: اجرای ثبت و دادگاه خانواده.\n\nدر مسیر اجرای ثبت، با ارائه سند ازدواج، اجرائیه صادر و در صورت نداشتن اموال، بازداشت تا سقف قانونی اجرا می‌شود.\n\nدر قانون جدید، نحوه مطالبه مهریه در صورت نداشتن توان مالی زوج اصلاح شده است؛ بنابراین آگاهی از قوانین روز اهمیت دارد.\n\nهمچنین مهریه می‌تواند عندالمطالبه یا عندالاستطاعه باشد که در نحوه وصول تفاوت دارد. وکیل خانواده می‌تواند بهترین مسیر را انتخاب کند.", readTime: 6, author: "دکتر لیلا صادقی", authorRole: "وکیل پایه یک", views: 14500, publishedAt: daysAgo(6) },
  { slug: "hazant-farzand-pas-az-jodayi", title: "حضانت فرزند پس از جدایی؛ قوانین و نکات", category: "خانواده", excerpt: "حضانت فرزند تا هفت‌سالگی با مادر است؛ اما بعد از آن چه؟ به پرسش‌های رایج حضانت پاسخ می‌دهیم.", content: "طبق قانون مدنی ایران، حضانت فرزند تا ۷ سالگی با مادر است (مگر مصلحت طفل خلاف آن اقتضا کند). پس از آن، حضانت با پدر خواهد بود، مگر دادگاه مصلحت را در نزد مادر بداند.\n\nدر صورت فوت هریک از والدین، حضانت به دیگری می‌رسد و در برخی موارد به جد پدری. دادگاه در تمام تصمیمات، مصلحت طفل را ملاک قرار می‌دهد.\n\nنکته مهم: ملاقات فرزند حق هر دو والد است و ممانعت از ملاقات، قابل تعقیب کیفری است.\n\nبرای تغییر حضانت یا تعیین تکلیف، ارائه دلایل مستند به دادگاه خانواده ضروری است. وکیل خانواده می‌تواند شما را همراهی کند.", readTime: 5, author: "دکتر لیلا صادقی", authorRole: "وکیل پایه یک", views: 13100, publishedAt: daysAgo(12) },
  { slug: "sabt-shirkat-marhal", title: "مراحل ثبت شرکت؛ از انتخاب نوع تا اتمام", category: "شرکت‌ها", excerpt: "ثبت شرکت با مسئولیت محدود یا سهامی خاص؟ مراحل، مدارک و هزینه‌ها را توضیح می‌دهیم.", content: "برای ثبت شرکت، نخست باید نوع آن را انتخاب کنید. رایج‌ترین نوع برای کسب‌وکارهای کوچک، مسئولیت محدود است.\n\nمراحل شامل: انتخاب نام و استعلام آن، تنظیم اساسنامه و شرکتنامه، اخذ مجوزها، ثبت در اداره ثبت شرکت‌ها و دریافت روزنامه رسمی است.\n\nپس از ثبت، تکالیفی مانند اخذ کد اقتصادی و ثبت در سامانه مالیاتی وجود دارد.\n\nتوجه به مسئولیت سهامداران در انواع شرکت مهم است؛ در مسئولیت محدود، مسئولیت تا میزان سرمایه است. وکیل متخصص شرکت‌ها می‌تواند فرایند را سریع پیش ببرد.", readTime: 6, author: "نگار سلیمانی", authorRole: "وکیل پایه یک", views: 8700, publishedAt: daysAgo(21) },
  { slug: "sharayet-shekat-keifari", title: "شرایط طرح شکایت کیفری چیست؟", category: "کیفری", excerpt: "چه زمانی می‌توان شکایت کیفری کرد؟ جرایم قابل گذشت و غیرقابل گذشت، مهلت‌ها و مدارک لازم.", content: "شکایت کیفری زمانی قابل طرح است که عمل ارتکابی در قانون جرم شناخته شده باشد. جرایم به دو دسته قابل گذشت و غیرقابل گذشت تقسیم می‌شوند.\n\nدر جرایم غیرقابل گذشت، تعقیب بدون شکایت شاکی نیز آغاز می‌شود؛ اما در جرایم قابل گذشت مانند برخی ضرب‌وجرح‌ها، شکایت شاکی شرط تعقیب است.\n\nمدارک لازم شامل ادله، مستندات، شهادت شهود و هر مدرکی که وقوع جرم را نشان دهد. مهلت شکایت در برخی جرایم وجود دارد.\n\nطرح شکایت از طریق دفاتر خدمات الکترونیک قضایی انجام می‌شود. وکیل کیفری در تنظیم شکواییه و جمع‌آوری ادله کمک مؤثری است.", readTime: 5, author: "حسین علمداری", authorRole: "وکیل پایه یک", views: 9400, publishedAt: daysAgo(28) },
  { slug: "hoqoq-malekat-fekri", title: "حقوق مالکیت فکری؛ از برند تا کپی‌رایت", category: "شرکت‌ها", excerpt: "مالکیت فکری چیست و چگونه از ایده، برند و آثار خود محافظت کنیم؟ راهنمای جامع.", content: "مالکیت فکری شامل حقوق ناشی از خلاقیت ذهنی است: علامت تجاری، طرح صنعتی، اختراع، کپی‌رایت و اسرار تجاری.\n\nثبت علامت تجاری از سوءاستفاده دیگران جلوگیری می‌کند. اختراع پس از ثبت، حق انحصاری بهره‌برداری می‌دهد. کپی‌رایت نیز بدون نیاز به ثبت، برای آثار ادبی و هنری ایجاد می‌شود.\n\nنقض حقوق مالکیت فکری، هم مسئولیت مدنی (جبران خسارت) و هم مسئولیت کیفری دارد.\n\nبرای حفظ حقوق خود، مستندسازی زمان خلق اثر و ثبت رسمی علائم بسیار مهم است. وکیل مالکیت فکری می‌تواند راهنمای شما باشد.", readTime: 5, author: "نگار سلیمانی", authorRole: "وکیل پایه یک", views: 6100, publishedAt: daysAgo(33) },
  { slug: "vadie-va-giro", title: "ودیعه و اجاره‌بها؛ قوانین جدید و نکات کاربردی", category: "ملک", excerpt: "سقف ودیعه و اجاره‌بها در سال جدید چگونه تعیین می‌شود؟ نکات حقوقی موجر و مستأجر.", content: "در شهرهای بزرگ، افزایش اجاره‌بها مطابق مصوبه دولت و تورم رسمی محدود شده است. ودیعه نیز سقف مشخصی دارد.\n\nموجر نمی‌تواند بیش از سقف اعلامی اجاره‌بها مطالبه کند؛ در غیر این صورت تخلف محسوب و جریمه دارد.\n\nمستأجر باید قرارداد را در سامانه املاک ثبت کند تا از حمایت قانونی برخوردار شود.\n\nبرای بازگرداندن ودیعه در پایان قرارداد، صورت‌جلسه تحویل و رفع خسارت‌ها اهمیت دارد. وکیل ملکی می‌تواند از حقوق شما در این فرایند محافظت کند.", readTime: 4, author: "ندا کریمی", authorRole: "وکیل پایه یک", views: 7900, publishedAt: daysAgo(36) },
  { slug: "taghsim-ers", title: "چگونه ارث را تقسیم کنیم؟", category: "ارث", excerpt: "راهنمای گام‌به‌گام انحصار وراثت و تقسیم ترکه میان وراث.", content: "پس از فوت شخص، نخستین گام اخذ «گواهی انحصار وراثت» از شورای حل اختلاف است. این گواهی وراث قانونی و سهم هریک را مشخص می‌کند.\n\nتا پیش از تعیین سهم‌الارث، هیچ‌یک از وراث حق تصرف انحصاری در اموال متوفی را ندارد. هرگونه تصرف، باید با رضایت سایر وراث یا حکم دادگاه باشد.\n\nپس از تعیین سهم، وراث می‌توانند با توافق، ترکه را تقسیم کنند. در صورت اختلاف، تقسیم از طریق دادگاه انجام می‌شود.\n\nتوجه به مسائل مالیاتی متوفی و پرداخت دیون پیش از تقسیم، از اهمیت بالایی برخوردار است. وکیل متخصص امور حسبی می‌تواند در این مسیر راهنمای شما باشد.", readTime: 5, author: "سارا موسوی", authorRole: "وکیل پایه یک", views: 5900, publishedAt: daysAgo(40) },
];

const qaData = [
  { slug: "check-bargasht-chi-konam", question: "اگر چک برگشت بخورد چه کنم؟", body: "چک ۵۰ میلیونی که از کارفرمام گرفته بودم برگشت خورده. مسیر قانونی چیست؟", answer: "نخست به بانک مراجعه و «گواهی عدم پرداخت» و نسخه اجرائیه را دریافت کنید. سپس می‌توانید از مسیر اجرائیه (سریع‌ترین روش وصول) یا شکایت کیفری/حقوقی اقدام کنید. برای طرح شکایت کیفری مهلت قانونی وجود دارد، بنابراین بدون تأخیر اقدام کنید. داشتن نشانی دقیق صادرکننده برای احضار ضروری است.", category: "چک و اسناد", lawyerName: "کاوه احمدی", lawyerTitle: "وکیل پایه یک — متخصص اسناد تجاری", verified: true, helpful: 48, views: 8200, createdAt: daysAgo(3) },
  { slug: "mostager-che-konam", question: "مستأجر من سه ماه اجاره نداده، چه کار کنم؟", body: "مستأجر سه ماه اجاره‌بها نپرداخته و قرارداد رسمی دارم.", answer: "اگر قرارداد رسمی و دارای شرط تخلیه دارید، می‌توانید از طریق شورای حل اختلاف محل ملک، دادخواست تخلیه و مطالبه اجاره‌بها ثبت کنید. پیش از آن، ارسال اظهارنامه و اخطار رسمی توصیه می‌شود. در صورت عدم رسیدگی، حکم تخلیه با حضور مأمور اجرا انجام می‌شود.", category: "ملک", lawyerName: "ندا کریمی", lawyerTitle: "وکیل پایه یک — متخصص حقوق ملک", verified: true, helpful: 36, views: 6100, createdAt: daysAgo(7) },
  { slug: "modat-talaq-tavafoghi", question: "برای طلاق توافقی چه مدت زمان لازم است؟", body: "زن و شردر همه امور توافق داریم. چقدر طول می‌کشد؟", answer: "در طلاق توافقی که توافق کامل وجود دارد، فرایند معمولاً بین ۱ تا ۳ ماه طول می‌کشد؛ شامل ثبت دادخواست، تعیین جلسه، حضور در مشاور الزامی، صدور گواهی عدم امکان سازش و ثبت در محضر. با تنظیم دقیق توافق‌نامه پیش از دادخواست، روند تسریع می‌شود.", category: "خانواده", lawyerName: "دکتر لیلا صادقی", lawyerTitle: "وکیل پایه یک — متخصص خانواده", verified: true, helpful: 41, views: 5400, createdAt: daysAgo(11) },
  { slug: "check-siyadi-chist", question: "چک صیادی چیست و چه تفاوتی با چک عادی دارد؟", body: "بانک گفت چک صیادی است. معنی‌اش چیست؟", answer: "چک صیادی چکی است که در سامانه صیاد ثبت می‌شود و اطلاعات صادرکننده و گیرنده در آن ثبت می‌گردد. این چک‌ها ردیابی آسان‌تری دارند و در صورت برگشت، امکان پیگیری قانونی قوی‌تری فراهم می‌شود. گواهی عدم پرداخت این چک‌ها هم از سامانه صیاد صادر می‌شود.", category: "چک و اسناد", lawyerName: "کاوه احمدی", lawyerTitle: "وکیل پایه یک", verified: true, helpful: 29, views: 4700, createdAt: daysAgo(14) },
  { slug: "elzam-be-tanzim-sand", question: "الزام به تنظیم سند چگونه است؟", body: "ملکی خریده‌ام اما فروشنده حاضر به تنظیم سند رسمی نیست.", answer: "اگر مبایعه‌نامه معتبر دارید، می‌توانید با دادخواست «الزام به تنظیم سند رسمی» در دادگاه محل وقوع ملک، فروشنده را ملزم کنید. در صورت امتناع وی، دادگاه حکم تنظیم سند را صادر می‌کند و انتقال بدون حضور او نیز ممکن می‌شود. داشتن مبایعه‌نامه و مدارک پرداخت ثمن ضروری است.", category: "ملک", lawyerName: "علیرضا بهرامی", lawyerTitle: "وکیل پایه یک — متخصص حقوق ملک", verified: true, helpful: 24, views: 3900, createdAt: daysAgo(18) },
  { slug: "khiyanat-dar-amanat", question: "خیانت در امانت چه زمانی محقق می‌شود؟", body: "سندی به کسی دادم که پس نداده. آیا خیانت در امانت است؟", answer: "خیانت در امانت زمانی محقق می‌شود که شخصی مالی که به عنوان امانت یا برای انجام کاری به او سپرده شده را پس ندهد یا مصرف کند. اثبات رابطه امانی و امتناع از بازگرداندن، ارکان جرم هستند. شکایت در دادسرا ثبت و در صورت احراز، تعقیب کیفری انجام می‌شود.", category: "کیفری", lawyerName: "حسین علمداری", lawyerTitle: "وکیل پایه یک — متخصص کیفری", verified: true, helpful: 19, views: 3300, createdAt: daysAgo(22) },
];

/* ----------------------------- Provisioning ----------------------------- */
// Idempotent schema creation (best-effort fallback for a fresh DB;
// drizzle-kit push is the primary source of truth).
const DDL = [
  `DO $$ BEGIN CREATE TYPE case_status AS ENUM ('new','reviewing','matched','active','closed'); EXCEPTION WHEN duplicate_object THEN null; END $$`,
  `DO $$ BEGIN CREATE TYPE consultation_type AS ENUM ('chat','voice','video'); EXCEPTION WHEN duplicate_object THEN null; END $$`,
  `DO $$ BEGIN CREATE TYPE consultation_status AS ENUM ('pending','confirmed','completed','cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$`,
  `CREATE TABLE IF NOT EXISTS lawyers (id SERIAL PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, avatar_color TEXT NOT NULL DEFAULT '#15365d', title TEXT NOT NULL DEFAULT 'وکیل پایه یک دادگستری', license_no TEXT NOT NULL, city TEXT NOT NULL, province TEXT NOT NULL, gender TEXT NOT NULL DEFAULT 'male', experience_years INTEGER NOT NULL DEFAULT 0, specialties TEXT[] NOT NULL DEFAULT '{}', rating REAL NOT NULL DEFAULT 0, review_count INTEGER NOT NULL DEFAULT 0, case_count INTEGER NOT NULL DEFAULT 0, price_chat INTEGER NOT NULL DEFAULT 0, price_voice INTEGER NOT NULL DEFAULT 0, price_video INTEGER NOT NULL DEFAULT 0, verified BOOLEAN NOT NULL DEFAULT true, top_rated BOOLEAN NOT NULL DEFAULT false, fast_responder BOOLEAN NOT NULL DEFAULT false, contract_expert BOOLEAN NOT NULL DEFAULT false, response_time TEXT NOT NULL DEFAULT 'کمتر از یک ساعت', bio TEXT NOT NULL DEFAULT '', about TEXT NOT NULL DEFAULT '', services TEXT[] NOT NULL DEFAULT '{}', views INTEGER NOT NULL DEFAULT 0, featured BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS reviews (id SERIAL PRIMARY KEY, lawyer_id INTEGER NOT NULL REFERENCES lawyers(id) ON DELETE CASCADE, client_name TEXT NOT NULL, rating INTEGER NOT NULL, comment TEXT NOT NULL, service TEXT, created_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS contracts (id SERIAL PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, category TEXT NOT NULL, icon TEXT NOT NULL DEFAULT 'file', description TEXT NOT NULL, use_case TEXT NOT NULL, risks TEXT[] NOT NULL DEFAULT '{}', key_clauses TEXT[] NOT NULL DEFAULT '{}', sample_price INTEGER NOT NULL DEFAULT 0, custom_price INTEGER NOT NULL DEFAULT 0, popular BOOLEAN NOT NULL DEFAULT false, steps TEXT[] NOT NULL DEFAULT '{}')`,
  `CREATE TABLE IF NOT EXISTS articles (id SERIAL PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, category TEXT NOT NULL, excerpt TEXT NOT NULL, content TEXT NOT NULL, read_time INTEGER NOT NULL DEFAULT 5, author TEXT NOT NULL DEFAULT 'تیم تحریریه شریفمند', author_role TEXT NOT NULL DEFAULT 'پژوهشگر حقوق', views INTEGER NOT NULL DEFAULT 0, published_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS qa_questions (id SERIAL PRIMARY KEY, slug TEXT NOT NULL UNIQUE, question TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', answer TEXT NOT NULL, category TEXT NOT NULL, lawyer_name TEXT NOT NULL, lawyer_title TEXT NOT NULL DEFAULT 'وکیل پایه یک', verified BOOLEAN NOT NULL DEFAULT true, helpful INTEGER NOT NULL DEFAULT 0, views INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS cases (id SERIAL PRIMARY KEY, case_number TEXT NOT NULL, subject TEXT NOT NULL, description TEXT NOT NULL, city TEXT NOT NULL, stage TEXT NOT NULL DEFAULT 'ثبت اولیه', budget TEXT, contact_name TEXT NOT NULL, contact_phone TEXT NOT NULL, status case_status NOT NULL DEFAULT 'new', created_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS consultations (id SERIAL PRIMARY KEY, lawyer_name TEXT, lawyer_id INTEGER, type consultation_type NOT NULL DEFAULT 'chat', duration INTEGER NOT NULL DEFAULT 30, client_name TEXT NOT NULL, client_phone TEXT NOT NULL, subject TEXT NOT NULL, scheduled_at TEXT, price NUMERIC(12,0) NOT NULL DEFAULT '0', status consultation_status NOT NULL DEFAULT 'pending', created_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS tickets (id SERIAL PRIMARY KEY, ticket_number TEXT NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL, category TEXT NOT NULL, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS page_views (id SERIAL PRIMARY KEY, path TEXT NOT NULL UNIQUE, views INTEGER NOT NULL DEFAULT 0, last_seen TIMESTAMP NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS app_users (id SERIAL PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, email TEXT UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'client', created_at TIMESTAMP NOT NULL DEFAULT now())`,
];

export interface SeedCounts {
  lawyers: number;
  reviews: number;
  contracts: number;
  articles: number;
  qa: number;
}

export function getCounts(): SeedCounts {
  return {
    lawyers: lawyerData.length,
    reviews: reviewData.length,
    contracts: contractData.length,
    articles: articleData.length,
    qa: qaData.length,
  };
}

async function insertAll() {
  await db.insert(lawyers).values(lawyerData);
  await db.insert(reviews).values(reviewData);
  await db.insert(contracts).values(contractData);
  await db.insert(articles).values(articleData);
  await db.insert(qaQuestions).values(qaData);
}

/** Manual re-seed: wipe and re-insert. */
export async function seedAll(): Promise<SeedCounts> {
  await db.execute(
    sql`TRUNCATE lawyers, reviews, contracts, articles, qa_questions RESTART IDENTITY CASCADE`,
  );
  await insertAll();
  return getCounts();
}

/**
 * Automatic provisioning: ensure tables exist and seed only if empty.
 * Safe to run on every server start.
 */
export async function ensureSeeded(): Promise<{ seeded: boolean; counts: SeedCounts }> {
  for (const stmt of DDL) {
    try {
      await db.execute(sql.raw(stmt));
    } catch {
      /* ignore — push is primary */
    }
  }
  try {
    const res = await db.execute(sql`SELECT COUNT(*)::int AS c FROM lawyers`);
    const arr = (res as { rows?: unknown[] }).rows ?? [];
    const c = Number((arr[0] as { c?: number })?.c ?? 0);
    // Always add missing articles/QA (new content), never overwrite existing.
    try {
      await db.insert(articles).values(articleData).onConflictDoNothing({ target: articles.slug });
      await db.insert(qaQuestions).values(qaData).onConflictDoNothing({ target: qaQuestions.slug });
    } catch {
      /* non-fatal */
    }
    if (c > 0) return { seeded: false, counts: getCounts() };
    await insertAll();
    return { seeded: true, counts: getCounts() };
  } catch {
    return { seeded: false, counts: getCounts() };
  }
}
